services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    env_file:
      -  .env
    networks:
      - my-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  my-network: