FROM alpine:latest

WORKDIR /app

RUN apk update \
    && apk add --no-cache \
        unzip \
        wget \
        bash

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip \
    && unzip terraform_1.0.0_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_1.0.0_linux_amd64.zip

COPY ./infrastructure /app

# Ejecutar Terraform
CMD ["bash", "-c", "terraform init && terraform apply -auto-approve"]

